allowBuilds:
  '@nestjs/core': true
  '@prisma/engines': true
  '@scarf/scarf': true
  argon2: true
  esbuild: true
  msgpackr-extract: true
  prisma: true
minimumReleaseAgeExclude:
  - '@aws-sdk/client-s3@3.1084.0'
  - '@aws-sdk/lib-storage@3.1084.0'
  - prettier@3.9.5
